# Generated by Django 2.2.6 on 2019-11-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmtb_app', '0003_auto_20191101_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tel_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
