# Generated by Django 2.2.6 on 2019-11-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmtb_app', '0004_auto_20191101_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
